name: Test

on:
    - push
    - pull_request

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: restore node modules
              uses: actions/cache@v4
              id: node-modules-cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

            - name: Install Deps
              if: steps.node-modules-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Run test
              run: npm run test
